### ISSUE TITLE
[1.3] Errors in plot_bloch_vector_spherical()

### ISSUE THREAD

**Issue by wanihakse** [qiskit-community/qiskit-textbook#1334]
### Describe the bug

Hello! I am a beginner with qiskit.
While working in Chapter 1.3 of Bloch sphere representation to show the 3D image, I got an error of "AttributeError: 'Arrow3D' object has no attribute 'do_3d_projection'"  and a blank figure.
I just used the original code with matplotlib to display. (Code and version info are pasted below.)
It would be very appreciated if you could tell me how to solve it.
Thanks a lot!

### To Reproduce

```
from qiskit_textbook.widgets import plot_bloch_vector_spherical
import matplotlib.pyplot as plt
from math import pi

coords = [pi/2,0,1] # [Theta, Phi, Radius]
plot_bloch_vector_spherical(coords)
plt.show()
```

### Expected behavior

D:\anaconda3\envs\qiskit-env\lib\site-packages\qiskit\visualization\bloch.py:397: MatplotlibDeprecationWarning: Axes3D(fig) adding itself to the figure is deprecated since 3.4. Pass the keyword argument auto_add_to_figure=False and use fig.add_axes(ax) to suppress this warning. The default value of auto_add_to_figure will change to False in mpl3.5 and True values will no longer work in 3.6.  This is consistent with other Axes classes.
  self.axes = Axes3D(self.fig, azim=self.view[0], elev=self.view[1])
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\anaconda3\envs\qiskit-env\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "D:\anaconda3\envs\qiskit-env\lib\tkinter\__init__.py", line 814, in callit
    func(*args)
  File "D:\anaconda3\envs\qiskit-env\lib\site-packages\matplotlib\backends\_backend_tk.py", line 251, in idle_draw
    self.draw()
  File "D:\anaconda3\envs\qiskit-env\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 9, in draw
    super().draw()
  File "D:\anaconda3\envs\qiskit-env\lib\site-packages\matplotlib\backends\backend_agg.py", line 436, in draw
    self.figure.draw(self.renderer)
  File "D:\anaconda3\envs\qiskit-env\lib\site-packages\matplotlib\artist.py", line 73, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "D:\anaconda3\envs\qiskit-env\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "D:\anaconda3\envs\qiskit-env\lib\site-packages\matplotlib\figure.py", line 2803, in draw
    mimage._draw_list_compositing_images(
  File "D:\anaconda3\envs\qiskit-env\lib\site-packages\matplotlib\image.py", line 132, in _draw_list_compositing_images       
    a.draw(renderer)
  File "D:\anaconda3\envs\qiskit-env\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "D:\anaconda3\envs\qiskit-env\lib\site-packages\mpl_toolkits\mplot3d\axes3d.py", line 447, in draw
    for artist in sorted(collections_and_patches,
  File "D:\anaconda3\envs\qiskit-env\lib\site-packages\mpl_toolkits\mplot3d\axes3d.py", line 436, in do_3d_projection
    return artist.do_3d_projection(renderer)
AttributeError: 'Arrow3D' object has no attribute 'do_3d_projection'
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\anaconda3\envs\qiskit-env\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "D:\anaconda3\envs\qiskit-env\lib\tkinter\__init__.py", line 814, in callit
    func(*args)
  File "D:\anaconda3\envs\qiskit-env\lib\site-packages\matplotlib\backends\_backend_tk.py", line 251, in idle_draw
    self.draw()
  File "D:\anaconda3\envs\qiskit-env\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 9, in draw
    super().draw()
  File "D:\anaconda3\envs\qiskit-env\lib\site-packages\matplotlib\backends\backend_agg.py", line 436, in draw
    self.figure.draw(self.renderer)
  File "D:\anaconda3\envs\qiskit-env\lib\site-packages\matplotlib\artist.py", line 73, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "D:\anaconda3\envs\qiskit-env\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "D:\anaconda3\envs\qiskit-env\lib\site-packages\matplotlib\figure.py", line 2803, in draw
    mimage._draw_list_compositing_images(
  File "D:\anaconda3\envs\qiskit-env\lib\site-packages\matplotlib\image.py", line 132, in _draw_list_compositing_images       
    a.draw(renderer)
  File "D:\anaconda3\envs\qiskit-env\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "D:\anaconda3\envs\qiskit-env\lib\site-packages\mpl_toolkits\mplot3d\axes3d.py", line 447, in draw
    for artist in sorted(collections_and_patches,
  File "D:\anaconda3\envs\qiskit-env\lib\site-packages\mpl_toolkits\mplot3d\axes3d.py", line 436, in do_3d_projection
    return artist.do_3d_projection(renderer)
AttributeError: 'Arrow3D' object has no attribute 'do_3d_projection'

### Version info

 DeprecationWarning: The package qiskit.aqua is deprecated. It was moved/refactored to qiskit-terra For more information see <https://github.com/Qiskit/qiskit-aqua/blob/main/README.md#migration-guide>
  warn_package('aqua', 'qiskit-terra')
{'qiskit-terra': '0.18.3', 'qiskit-aer': '0.9.1', 'qiskit-ignis': '0.6.0', 'qiskit-ibmq-provider': '0.18.1', 'qiskit-aqua': '0.9.5', 'qiskit': '0.32.1', 'qiskit-nature': None, 'qiskit-finance': None, 'qiskit-optimization': None, 'qiskit-machine-learning': None}

Other version info.
python 3.8.12 MSC v.1916 64 bit within anaconda 3
matplotlib           3.5.0
matplotlib-inline    0.1.3

**Comment by mariandumitrascu** [comment]
I had the same error and upgrading matplotlib to 3.5.1 fixes it.
You should do:

pip install -U matplotlib --prefer-binary

**Comment by paniash** [comment]
Hi @wanihakse! Looks like @mariandumitrascu has solved your issue. Nevertheless, I would recommend installing packages in a virtual environment, it generally avoids such issues.
